### ISSUE TITLE
time complex

### ISSUE THREAD

**Issue by ffredd** [sverma88/DeepCU-IJCAI19#1]
hi! If you retrain, how much time can you run

**Comment by sverma88** [comment]
Can you be more specific? Are you asking about the time to retrain that depends on the hardware and the size of data.

**Comment by ffredd** [comment]
Oh, sorry! I figured out what's wrong with me. However, I have a problem in the code.  In the "DeepCU.py" file, shouldn't lines 256-259 be the data of the validation set?

**Comment by sverma88** [comment]
Oouch, yes you are correct. That should be part of validation set but it will not make a much difference as those line will take a sample size of < 64 only once in calculation. 

Besides, thanks for picking that.

**Comment by ffredd** [comment]
I'm here again! You wrote in your paper that LMF can solve the problem of too large dimension, but the method you use in your code is still TFN, right? 
I've been learning tensor fusion recently and I'm learning your code~~~

**Comment by sverma88** [comment]
Correct, LMF is factorized version of TFN scheme-- you may understand that as performing principal component analysis but in the tensor space. 
In terms of differences between TFN, LMF, and DeepCU - refer to figure 2 in the paper. It is much expressive than the equations.
